remote_theme: mfcollins3/normal-blog-theme

google_analytics_id: UA-62548623-1

# GitHub Defaults
#
# The following settings are set by GitHub and cannot be changed.

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false

encoding: UTF-8
future: true
jailed: false
gfm_quirks: paragraph_end

kramdown:
  math_engine: mathjax # GitHub default; cannot be changed
  syntax_highlighter: rouge # GitHub default; cannot be changed
  input: GFM
  hard_wrap: false

exclude: [README.md, Gemfile, Gemfile.lock]
permalink: /blog/:year/:month/:day/:title.html

paginate: 10
paginate_path: "blog/page:num/"

brand: The Imaginary Road

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

defaults:
  -
    scope:
      path: ""
    values:
      theme: normal
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Michael F. Collins, III"
      author_first_name: "Michael"
      author_last_name: "Collins"
      author_gender: "male"
      twitter_creator: "mfcollins3"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Michael F. Collins, III"
      author_first_name: "Michael"
      author_last_name: "Collins"
      author_gender: "male"
      twitter_creator: "mfcollins3"
