exclude: [Rakefile, README.md, ./lib, _temp, src, server, package.json, bower.json, Gruntfile.coffee, Gemfile, Gemfile.lock, node_modules, bower_components, less, coffee]
include: [./css/lib]
permalink: /blog/:year/:month/:day/:title.html
markdown: redcarpet
highlighter: pygments

paginate: 10
paginate_path: "blog/page:num/"

brand: The Imaginary Road

excerpt_separator: <!--more-->

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      theme: normal
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Michael F. Collins, III"
      author_first_name: "Michael"
      author_last_name: "Collins"
      author_gender: "male"
      twitter_creator: "mfcollins3"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Michael F. Collins, III"
      author_first_name: "Michael"
      author_last_name: "Collins"
      author_gender: "male"
      twitter_creator: "mfcollins3"
